# 🔒 TRAIDER V1 - Dependabot Security Configuration
#
# Automated dependency management for institutional-grade security compliance.
# Monitors all package ecosystems with aggressive update schedules for security patches.
#
# Performance: Daily security updates, weekly feature updates
# Risk: CRITICAL - Automated security patches with manual review for major versions
# Compliance: All dependency updates logged and audited
#
# See: https://docs.github.com/en/code-security/dependabot
# Author: TRAIDER Team
# Since: 1.0.0-alpha

version: 2

updates:
  # =============================================================================
  # FRONTEND DEPENDENCIES (Node.js/npm) - AGGRESSIVE SECURITY UPDATES
  # =============================================================================
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Etc/UTC"
    
    # Aggressive security configuration
    open-pull-requests-limit: 25
    reviewers:
      - "traider-security-team"
    assignees:
      - "traider-lead-dev"
    
    # Security-focused commit messages
    commit-message:
      prefix: "security"
      prefix-development: "deps"
      include: "scope"
    
    # Enhanced labels for tracking
    labels:
      - "dependencies"
      - "security"
      - "automated"
      - "priority-high"
    
    # Allow all dependency types for comprehensive coverage
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
      - dependency-type: "all"
    
    # Optimized grouping for faster security resolution
    groups:
      critical-security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
      
      frontend-core:
        applies-to: version-updates
        patterns:
          - "next*"
          - "react*"
          - "@next/*"
          - "@react/*"
        update-types:
          - "patch"
          - "minor"
      
      security-tools:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "typescript*"
        update-types:
          - "patch"
          - "minor"
      
      testing-framework:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "playwright*"
          - "@playwright/*"
          - "jest*"
          - "@jest/*"
        update-types:
          - "patch"
          - "minor"

  # =============================================================================
  # BACKEND DEPENDENCIES (Python/pip) - ENHANCED SECURITY
  # =============================================================================
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Etc/UTC"
    
    open-pull-requests-limit: 20
    reviewers:
      - "traider-security-team"
    assignees:
      - "traider-backend-lead"
    
    commit-message:
      prefix: "security"
      prefix-development: "deps"
      include: "scope"
    
    labels:
      - "dependencies"
      - "backend"
      - "security"
      - "automated"
      - "priority-high"
    
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
      - dependency-type: "all"
    
    # Enhanced grouping for Python security
    groups:
      critical-security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
      
      fastapi-ecosystem:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "pydantic*"
          - "starlette*"
        update-types:
          - "patch"
          - "minor"
      
      database-security:
        patterns:
          - "psycopg*"
          - "sqlalchemy*"
          - "alembic*"
          - "asyncpg*"
        update-types:
          - "patch"
          - "minor"
      
      crypto-security:
        patterns:
          - "cryptography*"
          - "jwt*"
          - "passlib*"
          - "bcrypt*"
        update-types:
          - "patch"
          - "minor"
          - "major"
      
      ml-frameworks:
        patterns:
          - "torch*"
          - "tensorflow*"
          - "numpy*"
          - "pandas*"
          - "scikit-learn*"
        update-types:
          - "patch"
          - "minor"

  # =============================================================================
  # GITHUB ACTIONS DEPENDENCIES - IMMEDIATE SECURITY UPDATES
  # =============================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Etc/UTC"
    
    open-pull-requests-limit: 15
    reviewers:
      - "traider-devops-team"
    assignees:
      - "traider-ci-lead"
    
    commit-message:
      prefix: "security"
      prefix-development: "ci"
      include: "scope"
    
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
      - "automated"
      - "security"
      - "priority-critical"
    
    # Group Actions updates for security
    groups:
      actions-security:
        patterns:
          - "actions/*"
        update-types:
          - "patch"
          - "minor"
          - "major"
      
      security-actions:
        patterns:
          - "github/codeql-action*"
          - "ossf/scorecard-action*"
          - "snyk/actions*"
        update-types:
          - "patch"
          - "minor"
          - "major"

  # =============================================================================
  # INFRASTRUCTURE DEPENDENCIES (Docker) - SECURITY FOCUSED
  # =============================================================================
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Etc/UTC"
    
    open-pull-requests-limit: 10
    reviewers:
      - "traider-devops-team"
    assignees:
      - "traider-infrastructure-lead"
    
    commit-message:
      prefix: "security"
      prefix-development: "infra"
      include: "scope"
    
    labels:
      - "dependencies"
      - "infrastructure"
      - "docker"
      - "automated"
      - "security"
    
    groups:
      base-images:
        patterns:
          - "node*"
          - "python*"
          - "alpine*"
          - "ubuntu*"
        update-types:
          - "patch"
          - "minor"
          - "major"

# =============================================================================
# SECURITY CONFIGURATION NOTES
# =============================================================================
# 
# This configuration implements:
# 1. Daily security scans for all ecosystems
# 2. Aggressive grouping to reduce PR noise
# 3. Priority labeling for security issues
# 4. Comprehensive coverage of all dependency types
# 5. Immediate updates for critical security patches
# 
# Monitoring: All updates tracked in security dashboard
# Compliance: Meets institutional security requirements
# Performance: Optimized for minimal latency in security patches 