/**
 * @fileoverview Next.js TypeScript environment declarations
 * @module next-env
 * 
 * @description
 * Auto-generated TypeScript declarations for Next.js environment.
 * Provides type definitions for Next.js-specific globals and modules.
 * Essential for TypeScript compilation in Next.js applications.
 * 
 * @performance
 * - Latency target: N/A (compile-time only)
 * - Throughput: N/A (compile-time only)
 * - Memory usage: <1MB (compile-time only)
 * 
 * @risk
 * - Failure impact: LOW (TypeScript compilation only)
 * - Recovery strategy: Auto-regenerated by Next.js
 * 
 * @compliance
 * - Audit requirements: No
 * - Data retention: N/A
 * 
 * @see {@link https://nextjs.org/docs/basic-features/typescript}
 * @since 1.0.0
 * @author TRAIDER Team
 */

/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.
