replicaCount: 1

image:
  repository: your-org/traider
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress:
  enabled: false 