apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traider-monolith
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/traider.git
    targetRevision: main
    path: helm/traider-monolith
  destination:
    server: https://kubernetes.default.svc
    namespace: traider
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 