groups:
  - name: traider-latency-alerts
    rules:
      - alert: HighSignalToOrderLatencyP95
        expr: traider_response_time_p95_seconds{endpoint="/signals"} > 0.5
        for: 5m
        labels:
          severity: critical
          service: traider-backend
        annotations:
          summary: "High P95 signal → order latency"
          description: "P95 response time for signal generation API has exceeded 500ms for more than 5 minutes. Current value is {{ $value }}s."

      - alert: HighOrderExecutionLatencyP95
        expr: traider_response_time_p95_seconds{endpoint="/orders"} > 0.5
        for: 5m
        labels:
          severity: critical
          service: traider-backend
        annotations:
          summary: "High P95 order execution latency"
          description: "P95 response time for order execution API has exceeded 500ms for more than 5 minutes. Current value is {{ $value }}s." 