from typing import Dict, Any, AsyncGenerator
from fastapi import Depends, Query, FastAPI, HTTPException
from fastapi.responses import JSONResponse

app: FastAPI

async def db_dep() -> AsyncGenerator[Any, None]: ...

async def liveness() -> Dict[str, str]: ...
async def readiness(conn=Depends(...)) -> Dict[str, str]: ...
async def latest_market_data(symbol: str, limit: int = Query(...), conn=Depends(...)) -> Dict[str, Any]: ...
async def metrics_endpoint() -> JSONResponse: ...