# 🚀 TRAIDER V1 - Traefik Configuration
# Reverse proxy and load balancer with SSL termination
# Institutional-grade security and performance

# =============================================================================
# GLOBAL CONFIGURATION
# =============================================================================

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# =============================================================================
# API & DASHBOARD
# =============================================================================

api:
  dashboard: true
  insecure: true  # Only for development - use auth in production
  debug: true

# =============================================================================
# ENTRYPOINTS (Ports)
# =============================================================================

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        options: default

  traefik:
    address: ":8080"

# =============================================================================
# PROVIDERS
# =============================================================================

providers:
  # Docker provider for service discovery
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traider-network
    watch: true

  # File provider for static configuration
  file:
    directory: /etc/traefik/dynamic
    watch: true

# =============================================================================
# CERTIFICATE RESOLVERS (Let's Encrypt)
# =============================================================================

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@traider.local
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web
      # Use DNS challenge for production
      # dnsChallenge:
      #   provider: cloudflare
      #   delayBeforeCheck: 60

# =============================================================================
# LOGGING
# =============================================================================

log:
  level: INFO
  format: json
  filePath: /var/log/traefik.log

accessLog:
  format: json
  filePath: /var/log/access.log
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep

# =============================================================================
# METRICS & MONITORING
# =============================================================================

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# =============================================================================
# TRACING
# =============================================================================

tracing:
  jaeger:
    samplingServerURL: http://jaeger:14268/api/sampling
    localAgentHostPort: jaeger:6831

# =============================================================================
# SECURITY HEADERS
# =============================================================================

# Default security headers applied to all routes
# Additional headers configured in dynamic configuration 