from typing import Dict, Any
from fastapi.responses import JSONResponse, PlainTextResponse

async def health_check() -> JSONResponse: ...
async def liveness_probe() -> JSONResponse: ...
async def readiness_probe() -> JSONResponse: ...
async def detailed_health_check() -> JSONResponse: ...
async def prometheus_metrics() -> PlainTextResponse: ...

async def check_database_health() -> Dict[str, Any]: ...

def get_system_info() -> Dict[str, Any]: ... 