name: Flaky Test Detector

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  detect-flaky-tests:
    name: Detect Flaky Tests
    runs-on: ubuntu-latest
    continue-on-error: true  # Do not block main pipeline
    timeout-minutes: 30

    steps:
      - name: 游댃 Checkout repository
        uses: actions/checkout@v4

      - name: 游릭 Setup Node.js & pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: 游냀 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 游닌 Install JS/TS dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: 游닌 Install Python dependencies
        run: |
          python -m pip install -r apps/backend/requirements.txt
          python -m pip install pytest-repeat

      - name: 游대 Run Vitest suite 3x to detect flakes
        run: |
          for i in 1 2 3; do
            echo "Vitest run $i";
            pnpm exec vitest run || true;
          done

      - name: 游대 Run PyTest suite 3x to detect flakes
        run: |
          for i in 1 2 3; do
            echo "PyTest run $i";
            pytest -q || true;
          done

      - name: 游늵 Collate failure logs
        if: always()
        run: |
          mkdir -p flaky-report
          cp -r vitest-report* flaky-report/ || true
          cp -r .pytest_cache flaky-report/ || true

      - name: 游닋 Upload flaky test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flaky-test-report
          path: flaky-report/
          retention-days: 14 