name: Nightly Postgres Backup

on:
  schedule:
    - cron: '0 2 * * *'  # 02:00 UTC daily
  workflow_dispatch:

jobs:
  backup-postgres:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_BACKUP_KEY: ${{ secrets.DB_BACKUP_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run backup script
        run: bash scripts/backup-postgres.sh

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgres-backup-${{ github.run_id }}
          path: artifacts/*.enc
          retention-days: 7 